### ISSUE TITLE
all the functions return  {"_A": null, "_x": 0, "_y": 0, "_z": null}

### ISSUE THREAD

**Issue by sunset1234321** [maniac-tech/react-native-expo-read-sms#16]
all the functions return 
{"_A": null, "_x": 0, "_y": 0, "_z": null}

**Comment by maniac-tech** [comment]
@sunset1234321 Can you share a small reproducible example ?

**Comment by maniac-tech** [comment]
@sunset1234321 This looks to be a promise being returned, which is expected.

It'd be helpful to understand your issue if you share a reproducible example, or you may also refer to the example of how to use this.

**Comment by maniac-tech** [comment]
Will be closing this issue as `Not an issue` by 10th Nov, if there is no more conversation here.
