### ISSUE TITLE
I found this issue while installing this tool

### ISSUE THREAD

**Issue by vardhan124** [maniac-tech/react-native-expo-read-sms#19]
**Screenshots**

![image](https://user-images.githubusercontent.com/53694696/214260420-45671dc7-4837-4c35-8442-2fa1b6a67a0f.png)

**Comment by maniac-tech** [comment]
Is the project publicly available @vardhan124 ?

**Comment by vardhan124** [comment]
> Is the project publicly available @vardhan124 ?

no bro 🤥

**Comment by vardhan124** [comment]
Currently I am Developing it .. . Still have to do allot
That why I' didn't published yet

**Comment by vardhan124** [comment]
But If u want i can Publish It in Expo publish .....

**Comment by maniac-tech** [comment]
No, what I meant by availability is whether the source code open and available on Github.

If not, can you create a small reproduction of it and share it here ?

**Comment by onur-celik** [comment]
Not sure if it's safe but I've installed the library using --force command and I worked.

**Comment by maniac-tech** [comment]
> Not sure if it's safe but I've installed the library using --force command and it worked.

Can you share a small reproduction of it?

**Comment by maniac-tech** [comment]
The error log shared in the original description mentions that there is a conflict of dependencies.

A simple way to resolve this temporarily is to use the attribute `--force`or `--legacy-peer-deps`along with `npm install`
The final command will look like: `npm install --force`/ `npm install --legacy-peer-deps`

Engineers are expected to install peer dependencies manually, this change was introduced in v3.x, and has been updated in v7.x of npm.

You may use the temporary solution for now, till I raise a PR to start using v7.x and above.

**Comment by maniac-tech** [comment]
Closing this as the peer dependencies has been updated in the PR #26
