### ISSUE TITLE
Unable to install the library 

### ISSUE THREAD

**Issue by akki251** [maniac-tech/react-native-expo-read-sms#21]
**Describe the bug**
I created a brand new app for expo using this command
```npx create-expo-app my-app```
and tried to install the package
```npm install @maniac-tech/react-native-expo-read-sms --save```

**To Reproduce**
You can follow above steps

**Expected behavior**
No error should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/67007034/220301738-afc29fe4-32ea-41f9-987e-8525664cd859.png)

**Additional context**
The temporary fix would be use npm i --force, but then I won't be able to build an app with it, as expo build uses npm i, which would result in an error

**Comment by akki251** [comment]
Fixed, It was something react specific

**Comment by maniac-tech** [comment]
@akki251 : Yes this is an unrelated to the library, but [this](https://github.com/maniac-tech/react-native-expo-read-sms/issues/19#issuecomment-1439023747) might be of some help to you.

**Comment by syeed111** [comment]
> **Describe the bug** I created a brand new app for expo using this command `npx create-expo-app my-app` and tried to install the package `npm install @maniac-tech/react-native-expo-read-sms --save`
> 
> **To Reproduce** You can follow above steps
> 
> **Expected behavior** No error should be there
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/67007034/220301738-afc29fe4-32ea-41f9-987e-8525664cd859.png)
> 
> **Additional context** The temporary fix would be use npm i --force, but then I won't be able to build an app with it, as expo build uses npm i, which would result in an error

I am facing the same issue , how did you build it ?

**Comment by maniac-tech** [comment]
@syeed111 you simply install the library in your application and go about building it the way you usually do it.

What you need to watch out for is the React versions.
