### ISSUE TITLE
Error while building using expo

### ISSUE THREAD

**Issue by akki251** [maniac-tech/react-native-expo-read-sms#22]
I used 
```eas build --profile development --platform android for building the app```

It gave me this error : 
![image](https://user-images.githubusercontent.com/67007034/220308847-1395a5b4-0b8d-44ca-a793-573a0c19a663.png)

**Comment by maniac-tech** [comment]
Thank for sharing the log @akki251 

Let me check this and get back to you.

**Comment by maniac-tech** [comment]
This is not related to the package.
Closing this.
