### ISSUE TITLE
Read old SMS messages

### ISSUE THREAD

**Issue by h13e** [maniac-tech/react-native-expo-read-sms#30]
**Describe the solution you'd like**
I'd like to be able to access old SMS messages (e.g. the last x messages from a given contact) as opposed to listening for present/incoming messages.

**Additional context**
Is this functionality already supported? It didn't seem to be the case based on the README.

**Comment by maniac-tech** [comment]
@h13e Can you elaborate on the use case here ?

The library currently only reads incoming messages.

**Comment by h13e** [comment]
@maniac-tech sure my main understanding (or assumption) was that this library was the expo equivalent of `react-native-get-sms-android`. 

So if I wanted an app to read older messages (say the last 10 messages from a contact) on a device, to analyze how often the user and the contact text each other, I thought that I could use this library for that in expo (given the fact that expo doesn't support this out the box).

**Comment by maniac-tech** [comment]
@h13e : That isn't the use case I had in mind when I wrote this. Have you checked why isn't expo supporting this at the moment ?

**Comment by h13e** [comment]
@maniac-tech It's likely due to security concerns. Thanks for getting back to me. I'll close this now.

**Comment by maniac-tech** [comment]
Feel free to ping me if you need help with your problem statement @h13e, more than happy to help solve a problem 🥂
