### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 1)

### ISSUE THREAD

**Issue by Musaiyib** [maniac-tech/react-native-expo-read-sms#32]
This is the error that i'm receiving from my android virtual device
WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'startReadSMS' of null
TypeError: Cannot read property 'startReadSMS' of null

and this is the error i'm getting from my iphone
"PermissionsAndroid" module works only for Android platform.     
 LOG  READ_SMS_PERMISSION_STATUS, RECEIVE_SMS_PERMISSION_STATUS: null false

**Comment by maniac-tech** [comment]
Can you share the project details ?

What version you are on and the device details along withAPI information.

**Comment by maniac-tech** [comment]
Will close this issue if there are no updates in the next 2 Days.

**Comment by maniac-tech** [comment]
Closing this due to no further updates.
