### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Rinno399** [maniac-tech/react-native-expo-read-sms#39]
# error in installation

React-native version - 0.72.6

It is log :
'Log files:
C:\Users\BTC\AppData\Local\npm-cache\_logs\2024-01-03T13_31_41_622Z-debug-0.log

# npm resolution error report
While resolving: app_one@1.0.0
Found: react-native@0.72.6
node_modules/react-native
  react-native@"0.72.6" from the root project

Could not resolve dependency:
peer react-native@"^0.69.9" from @maniac-tech/react-native-expo-read-sms@2.0.0
node_modules/@maniac-tech/react-native-expo-read-sms
  @maniac-tech/react-native-expo-read-sms@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by maniac-tech** [comment]
@Rinno399 : Im currently looking into this. Will update here as I make progress....

**Comment by maniac-tech** [comment]
@Rinno399 I have released a new version v3.0 of the library.

Can you try with the new version?

**Comment by maniac-tech** [comment]
@Rinno399 Any update ?

**Comment by maniac-tech** [comment]
Closing this due to no updates.
