### ISSUE TITLE
Support for EXPO SDK 51 or a walkaround to use the package?

### ISSUE THREAD

**Issue by rohith02b** [maniac-tech/react-native-expo-read-sms#47]
I'm am unable to install this package on expo SDK 51
I'd like Support for Expo SDK 51

**Comment by maniac-tech** [comment]
I intend to support the package on v51.

Looking to the next week to release it.

**Comment by maniac-tech** [comment]
In the meantime if you are facing any issues, please share them here. Might help speed up the development.

**Comment by rohith02b** [comment]
Cool , Thanks!

**Comment by maniac-tech** [comment]
The package has been updated to support v48, and v49 is being worked upon. We should be able to reach v51 soon.

**Comment by rohith02b** [comment]
That's great, Thanks for the effort!

**Comment by maniac-tech** [comment]
> That's great, Thanks for the effort!

In the meantime, do help me by sharing any feedback on [documentation](https://maniac-tech.com/expo-read-sms/docs), or any features you think should be available

**Comment by rohith02b** [comment]
The documentation is perfect!, Cool package man!

**Comment by maniac-tech** [comment]
Closing this as the version has been released.
