### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by syeed111** [maniac-tech/react-native-expo-read-sms#70]
Request for Help: Any insights or suggestions to resolve this build failure would be greatly appreciated. Thank you for your time and support!

**Environment:**
- Gradle version: 8.8
- Java version:  "22.0.1"
- OS: windows  10

**Dependency**
"dependencies": {
    "@maniac-tech/react-native-expo-read-sms": "^8.0.2-alpha",
    "expo": "^51.0.0",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "expo-build-properties": "~0.12.3",
    "expo-dev-client": "~4.0.19",
    "expo-splash-screen": "~0.27.5",
    "expo-updates": "~0.25.18",
    "react-dom": "18.2.0",
    "react-native-paper": "^4.12.2",
    "react-native-web": "~0.19.6"
  },
**Screen shot**

<img width="731" alt="gradle-build-fail" src="https://github.com/user-attachments/assets/e062cb97-a2e2-4a6b-9176-71a53e6b6f07">

** my github repo**
https://github.com/syeed111/Read-sms

**Comment by syeed111** [comment]
Gradle log file:https://docs.google.com/document/d/1K-4Qg3h7BUq4WIzEnrlvOKK_7zda9fMIrDx08D7fpa4/edit?usp=sharing

**Comment by maniac-tech** [comment]
The alpha version might be quite unstable @syeed111 . Try building with the last stable version.

**Comment by syeed111** [comment]
I have tried with version 8.0.0 and 7.0.0 . The result is same . do I have to modify androidManifest or mainActivity? 
I have tried to build your testapp:https://github.com/maniac-tech/ExpoReadSMS-TestApp/releases/tag/v7.0.0 . It shows wrong eas account .

**Comment by kenziy** [comment]
Do this have a solution? I also experience the same issue also using 7.0.0

**Comment by maniac-tech** [comment]
@syeed111 @kenziy : Can you share logs ?

**Comment by syeed111** [comment]
> Gradle log file:https://docs.google.com/document/d/1K-4Qg3h7BUq4WIzEnrlvOKK_7zda9fMIrDx08D7fpa4/edit?usp=sharing

I have copied  the log file into a text file and shared it here .

**Comment by maniac-tech** [comment]
> > Gradle log file:https://docs.google.com/document/d/1K-4Qg3h7BUq4WIzEnrlvOKK_7zda9fMIrDx08D7fpa4/edit?usp=sharing
> 
> I have copied the log file into a text file and shared it here .

This is the problem:

```
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 23 cannot be smaller than version 34 declared in library [:maniac-tech_react-native-expo-read-sms] /home/expo/workingdir/build/node_modules/@maniac-tech/react-native-expo-read-sms/android/build/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 23
  	Suggestion: use a compatible library with a minSdk of at most 23,
  		or increase this project's minSdk version to at least 34,
  		or use tools:overrideLibrary="com.reactlibrary" to force usage (may lead to runtime failures)
```

Your application is running on sdk 23, and the lib version is on 34, hence the failure.

**Comment by syeed111** [comment]
Abhishek Sir , Thanks for your co-operation .I will try your suggestion soon .

**Comment by maniac-tech** [comment]
> Abhishek Sir , Thanks for your co-operation .I will try your suggestion soon .

Let me know if it works for you or not.
